#%RAML 1.0 Library
uses:
  meta: meta.raml
(meta.module):  keras.callbacks
types:
  Callback:
    type: object
  CallbackWithPatience:
    type: Callback
    properties:
      patience:
        type: integer
      verbose:
        type: integer
        enum: [0,1]
      monitor:
        type: string
      mode:
        type: string
        enum: [min,max,auto]
        default: auto
  TensorBoard:
    type: Callback
    properties:
       log_dir: string
       histogram_freq?: integer
       batch_size?: integer
       write_graph: boolean
       write_grads?: boolean
       write_images?: boolean
       embeddings_freq?: number
       embeddings_layer_names?: string[]
       embeddings_metadata?: object
       embeddings_data?: object
       update_freq?:
         type: string
         enum: ['epoch','batch']
  EarlyStopping:
    type: CallbackWithPatience
  ReduceLROnPlateau:
    type: CallbackWithPatience
    properties:
      factor:
        type: number
        minimum: 0
        maximum: 1
      cooldown:
        type: integer
        minimum: 0
  CyclicLR:
    type: Callback
    properties:
      base_lr: number
      max_lr: number
      mode:
        type: string
        enum: [triangular,triangular2,exp_range]
      gamma:
        type: number
        minimum: 0
        maximum: 1
      step_size:
        type: integer
        minimum: 0
  CallbackModule:
    type: Callback
    properties:
      relSize?: number
      absSize?: number
      periodEpochs?: number
      periodSteps?: number
  LRVariator:
    type: CallbackModule
    properties:
      fromVal?: number
      toVal: number
      style?: string | number