#%RAML 1.0 Library
uses:
  meta: meta.raml
  generic: generic.raml
(meta.module):  instance_segmentation_pipeline.instance_segmentation
types:
  InstanceSegmentationPipeline:
    (meta.entry): true
    type: generic.GenericPipeline
    properties:
      inference_batch:
        (meta.custom): true
      testSplit?:
        (meta.custom): true
      testSplitSeed?:
        (meta.custom): true
      steps_per_epoch:
        type: integer
        (meta.custom): true
      backbone:
        type: string
        enum: [ resnet101, resnet50 ]
        (meta.custom): true
      validation_steps:
        type: integer
        (meta.custom): true
      weights?:
        enum: [imagenet, coco]
      crops?:
        type: integer
        (meta.custom): true
      shape:
        (meta.alias): input_shape
        type: meta.image_shape
