#%RAML 1.0 Library
uses:
  meta: meta.raml
  generic: generic.raml
(meta.module):  mmdetection_pipeline.mmdetection
types:
  PipelineConfig:
    (meta.entry): true
    type: generic.GenericPipeline
    properties:
      configPath:
      weightsPath?:
      imagesPerGpu?: integer
      multiscaleMode?:
      resetHeads?: boolean
      dropSemanticHead?: boolean
      threshold?: number
